cms8080:
  build: ./
  environment:
    PORT: 8080
    PROFILE: ubox
    aliyunOssAccessKeyId: $aliyunOssAccessKeyId
    aliyunOssSecretAccessKey: $aliyunOssAccessKeyId
  ports:
  - 8080:8080

#cms9090:
#  build: ./
#  environment:
#    PORT: 9090
#    PROFILE: ubox
#    aliyunOssAccessKeyId: $aliyunOssAccessKeyId
#    aliyunOssSecretAccessKey: $aliyunOssAccessKeyId
#  ports:
#  - 9090:9090

#nginx:
#  image: nginx
#  volumes:
#    - ./nginx.conf:/etc/nginx/nginx.conf
#  ports:
#    - "80:80"
# 运行命令如下：
# aliyunOssAccessKeyId=your-keyId aliyunOssSecretAccessKey=your-access-key docker-compose.exe up --build