apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: jast90/post-service
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: post
  labels:
    app: post
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
  selector:
    app: post
