# open service
apiVersion: v1
kind: Service
metadata:
  name: open
  labels:
    app: open
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: open

---
# account service
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: account

---
# post service
apiVersion: v1
kind: Service
metadata:
  name: post
  labels:
    app: post
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: post

---
# payment service
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: payment

---
# product service
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: product

---
# store service
apiVersion: v1
kind: Service
metadata:
  name: store
  labels:
    app: store
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: store

---
# mq service
apiVersion: v1
kind: Service
metadata:
  name: mq
  labels:
    app: mq
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: mq
