apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: jast90/account-service
          ports:
            - containerPort: 8081
          env:
            - name: oauth2-url
              valueFrom:
                configMapKeyRef:
                  name: oauth2
                  key: oauth2-url
---
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
  selector:
    app: account
