apiVersion: v1
kind: ConfigMap
metadata:
  name: account
data:
  application.properties: |-
    spring.datasource.username=root
    spring.datasource.password=123456
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.datasource.url=jdbc:mysql://mysql/account?useUnicode=yes&characterEncoding=UTF-8
    security.oauth2.resource.token-info-uri=http://${oauth2.server.host}/oauth/token
    security.oauth2.resource.prefer-token-info=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: jast90/account-service
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
  selector:
    app: account
