apiVersion: apps/v1
kind: Deployment
metadata:
  name: aliyun
  labels:
    app: aliyun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aliyun
  template:
    metadata:
      labels:
        app: aliyun
    spec:
      containers:
        - name: account
          image: jast90/aliyun-service
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: aliyun
  labels:
    app: aliyun
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
  selector:
    app: aliyun
