apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: jast90/express-service
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: express
  labels:
    app: express
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      protocol: TCP
  selector:
    app: express
