apiVersion: v1
kind: ConfigMap
metadata:
  name: mall-api
data:
  application.properties: |-
    security.oauth2.resource.token-info-uri=open/oauth/token
    security.oauth2.resource.prefer-token-info=true
    security.oauth2.resource.user-info-uri=open/user
    security.oauth2.client.client-id=mall-api
    security.oauth2.client.client-secret=mall-api-123
    security.oauth2.client.scope=all
    security.oauth2.client.access-token-uri=open/oauth/token
    security.oauth2.client.feign.client-id=mall-api
    security.oauth2.client.feign.client-secret=mall-api-123
    security.oauth2.client.feign.grant-type=client_credentials
    security.oauth2.client.feign.scope=all
    security.oauth2.client.feign.access-token-uri=open/oauth/token
    security.oauth2.client.feign.user-authorization-uri=open/oauth/authorize
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-api
  labels:
    app: mall-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-api
  template:
    metadata:
      labels:
        app: mall-api
    spec:
      containers:
        - name: account
          image: jast90/mall-api
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: mall-api
  labels:
    app: mall-api
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      protocol: TCP
  selector:
    app: mall-api
