apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq
  labels:
    app: mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
        - name: mq
          image: jast90/mq-service
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: mq
  labels:
    app: mq
spec:
  type: LoadBalancer
  ports:
    - port: 8084
      protocol: TCP
  selector:
    app: mq
