apiVersion: v1
kind: ConfigMap
metadata:
  name: open
  namepsace: default
data:
  application.properties: |-
    spring.datasource.username=root
    spring.datasource.password=123456
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.datasource.url=jdbc:mysql://mysql/open?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    security.oauth2.resource.token-info-uri=http://${oauth2.server.host}/oauth/token
    security.oauth2.resource.prefer-token-info=true
    security.oauth2.client.feign.client-id=account
    security.oauth2.client.feign.client-secret=account
    security.oauth2.client.feign.grant-type=client_credentials
    security.oauth2.client.feign.scope=all
    security.oauth2.client.feign.access-token-uri=http://${my.service.host}:8888/oauth/token
    security.oauth2.client.feign.user-authorization-uri=http://${my.service.host}:8888/oauth/authorize
    spring.redis.host=192.168.36.34
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open
  namepsace: default
  labels:
    app: open
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open
  template:
    metadata:
      labels:
        app: open
    spec:
      containers:
        - name: open
          image: jast90/open-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: open
  namepsace: default
  labels:
    app: open
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: open
