apiVersion: apps/v1
kind: Deployment
metadata:
  name: open
  labels:
    app: open
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open
  template:
    metadata:
      labels:
        app: open
    spec:
      containers:
        - name: open
          image: jast90/open-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: open
  labels:
    app: open
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: open
