apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss
  labels:
    app: oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oss
  template:
    metadata:
      labels:
        app: oss
    spec:
      containers:
        - name: oss
          image: jast90/oss-service
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: oss
  labels:
    app: oss
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      protocol: TCP
  selector:
    app: oss
